# Generated by Django 5.2 on 2025-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_historicalauthor_historicalbook_historicalreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
